name: GraphQL
on:
  schedule:
    - cron: "*/30 * * * *"
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-node@v2-beta
      - name: Sync the GraphQL schema
        run: npx get-graphql-schema https://api.loop.page > auto.graphql
      - name: Check if there are changes
        id: changes
        uses: UnicornGlobal/has-changes-action@v1.0.11
      - name: PR on changes
        if: steps.changes.outputs.changed == 1
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: Sync GraphQL Schema
          branch: sync/schema
          delete-branch: true
          title: Sync GraphQL Schema
          body: Automated syncing of GraphQL Schema. `auto.graphql` should be the only file changed.
          
